import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Navbar";
import Providers from "../components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Full Stack To_Do",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // o '/favicon.png'
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
    text-white
    min-h-screen bg-[radial-gradient(circle_at_center,_#041424,_#051320,_#080d13)]
    flex flex-col`}
      >
        <Providers>
          <Nav />

          <main className="flex-1">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
